version: "3"

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - app-network
  backend:
    build: ./backend/
    volumes:
      - ./backend/:/usr/src/app
    working_dir: /usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm rebuild bcrypt --build-from-source
        npm start
    networks:
      - app-network
    depends_on:
      - mongo
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/usr/src/app
    working_dir: /usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
    networks:
      - app-network
    depends_on:
      - backend
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certs:/etc/certs
    depends_on:
      - mongo
      - frontend
      - backend
    networks:
      - app-network
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
